version: '3'

####
#### this docker-compose can be used to start the petclinic with a plain mysql that is populated on application startup
####

services:
   mysql:
     image: mysql:5.7.8
     environment:
       MYSQL_ROOT_PASSWORD: petclinic
       MYSQL_DATABASE: petclinic
     networks:
      - samplenet

   petclinic:
     depends_on:
       - mysql
     build: 
       context: .
       args:
         url : https://github.com/gilleslabs/spring-petclinic.git
         project: spring-petclinic
         artifactid: spring-petclinic
         version: 2.1.0
     networks:
      - samplenet
     ports:
       - "8080:8080"
networks:
  samplenet:
    driver: bridge